#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"


/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/palette.h"
#include "images/square.h"
#include "images/startScreen.h"
#include "images/cursor.h"


/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
};

Cursor pointer;

// Load initial application state
  enum gba_state state = START;
  int time = 0;
  int wait;
  

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;
  u16 chosenColor;  
  char result[30];
  

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();
    

    switch (state) {
      case START:
        
        drawFullScreenImageDMA(startScreen);
        pointer.x = 50;
        pointer.y = 50;

        if (KEY_DOWN(BUTTON_START, BUTTONS)) {
          state = PLAY;
          
        }
        break;
      case PLAY:


        
        time = 0;
        wait = 0;
        

        while(1) {

          waitForVBlank();
          
          time++;

          
          
            
            
            drawString(10, 10, "seconds passed: ", BLACK);
            //drawRectDMA(8, 98, 40, 12, WHITE);
            undrawImageDMA(8, 98, 40, 12, palette);  
            sprintf (result, "%i", time / 60);
            drawString(10, 100, result, BLACK); 
          
          

          
        //drawRectDMA(20, 100, 20, 20, GRAY);
        
        if (time == 1) {
          drawFullScreenImageDMA(palette);
          drawString(10, 100, result, BLACK); 
          
          drawImageDMA(pointer.y, pointer.x, 7, 7, cursor);
        }
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          state = START;
          
        } else if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
          //if (pointer.x < 240) {
            //drawRectDMA(pointer.y, pointer.x, 7, 7, WHITE);
            undrawImageDMA(pointer.y, pointer.x, 7, 7, palette);
            pointer.x = pointer.x + 1;
            wait = 1;
            
            
            drawImageDMA(pointer.y, pointer.x, 7, 7, cursor);
          //}
        } else if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
          if (pointer.x > 0) {
            //drawRectDMA(pointer.y, pointer.x, 7, 7, WHITE);
            undrawImageDMA(pointer.y, pointer.x, 7, 7, palette);
            pointer.x = pointer.x - 1;
            wait = 1;
            
            drawImageDMA(pointer.y, pointer.x, 7, 7, cursor);
          }
        } else if (KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
          if (pointer.y < 170) {
            //drawRectDMA(pointer.y, pointer.x, 7, 7, WHITE);
            undrawImageDMA(pointer.y, pointer.x, 7, 7, palette);
            pointer.y = pointer.y + 1;
            wait = 1;
            
            drawImageDMA(pointer.y, pointer.x, 7, 7, cursor);
          }
        } else if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
          if (pointer.y > 0) {
            //drawRectDMA(pointer.y, pointer.x, 7, 7, WHITE);
            undrawImageDMA(pointer.y, pointer.x, 7, 7, palette);
            pointer.y = pointer.y - 1;
            wait = 1;
            
            drawImageDMA(pointer.y, pointer.x, 7, 7, cursor);

          } 
        } else if (KEY_DOWN(BUTTON_START , BUTTONS) && wait == 1 ) {
          chosenColor = getPixel(pointer.y, pointer.x, palette);
          fillScreenDMA(chosenColor);
          
          drawString(11, 31, "Press backspace to return", BLACK);
          drawString(10, 30, "Press backspace to return", WHITE);
          drawString(81, 44, "This is your chosen color!", GRAY);
          drawString(80, 43, "This is your chosen color!", WHITE);
          
          state = WIN;
          break;
        }


      }
        
        break;
      case WIN:
        
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
          state = START;
          
        }
        
        break;
    }

    
  }


 

  UNUSED(previousButtons); // You can remove this once previousButtons is used
  UNUSED(currentButtons); // You can remove this once previousButtons is used

  return 0;
}

 void mainScreen(void) {

      time = 0;


      



  }